### ISSUE TITLE
listview  can  loadmore ？

### ISSUE THREAD

**Issue by anjiao** [XavierSAndroid/MagicHeaderViewPager#2]
I see the demo can refresh ，listview  can have loadmore view ？

**Comment by XAVlER-S** [comment]
What do you mean by loadmore, on scroll to some position or pull up to load more?

**Comment by anjiao** [comment]
pull up to load more

**Comment by XAVlER-S** [comment]
I'm sorry, currently no test for pull up to load more, maybe yes in the future: )
