### ISSUE TITLE
刷新listview会返回到最顶部

### ISSUE THREAD

**Issue by GalvinChen** [XavierSAndroid/MagicHeaderViewPager#5]
在初始化完成后，调用listview的mAdapter.notifyDataSetChanged();
mMagicHeaderViewPager会scroll到header的最顶部，而且不好
拿到Scroll值，怎么让listview刷新时保持mMagicHeaderViewPager原来的位置不变

**Comment by XAVlER-S** [comment]
把相关的调用的代码都贴一下吧，最好是复制粘贴不要修改，便于定位问题

**Comment by GalvinChen** [comment]
mLvComment.setSelection(0);调用这句话就会返回到顶部
其实我想知道怎么直接定位到listview部分，就像新浪微博那样

**Comment by XAVlER-S** [comment]
调用这句话肯定会回到顶部的，试一下mLvComment.scrollToInnerTop()

**Comment by GalvinChen** [comment]
好的，谢谢
